### ISSUE TITLE
GItHub Desktop

### ISSUE THREAD

**Issue by miyamaru-yuuki** [miyamaru-yuuki/omikuji#2]
GItHub Desktop上によくわからないファイルが残っているのですがこれらはどうすればよいでしょうか？

![2019-01-27 12 37 16](https://user-images.githubusercontent.com/37493522/51796131-819f8300-2230-11e9-955d-c0db266be3ef.png)

**Comment by koharas** [comment]
.DS_StoreはMacで必要になるファイルで開発には不要です。
右クリックして、Ignore file で無視するように設定してください。
そうすると、.gitignoreというファイルにその設定が保存されます。

.gitignore 自体はgitの設定ファイルですので、これはpushしてwebにも保存しておきます。
一度設定すれば.DS_Storeは今後無視されるようになります。

**Comment by miyamaru-yuuki** [comment]
解決しました。
